#![allow(non_snake_case)]

use std::collections::{HashMap, HashSet};

use super::ast::*;
use super::diagnostic::SdslvDiagnostic;
use super::token::SdslvSpan;
use super::validation::ValidateModule;

pub fn EmitHlsl(module: &SdslvModule) -> Result<String, Vec<SdslvDiagnostic>> {
    if let Err(diagnostics) = ValidateModule(module) {
        return Err(diagnostics);
    }

    let mut emitter = HlslEmitter::New(module);
    emitter.Emit();
    emitter.Finish()
}

pub fn CompileSourceToHlsl(source: &str) -> Result<String, Vec<SdslvDiagnostic>> {
    let module = super::parser::ParseSource(source)?;
    ValidateModule(&module)?;
    EmitHlsl(&module)
}

#[derive(Clone)]
struct FlowLowerContext<'a> {
    StateByName: HashMap<String, &'a SdslvFlowState>,
    Visiting: HashSet<String>,
}

struct HlslEmitter<'a> {
    Module: &'a SdslvModule,
    AliasByName: HashMap<String, &'a SdslvTypeAliasDecl>,
    Lines: Vec<String>,
    Diagnostics: Vec<SdslvDiagnostic>,
}

impl<'a> HlslEmitter<'a> {
    fn New(module: &'a SdslvModule) -> Self {
        let mut alias_by_name = HashMap::new();
        for decl in &module.Declarations {
            if let SdslvDecl::TypeAlias(alias) = decl {
                alias_by_name.insert(alias.Name.clone(), alias);
            }
        }
        Self {
            Module: module,
            AliasByName: alias_by_name,
            Lines: vec![],
            Diagnostics: vec![],
        }
    }

    fn Emit(&mut self) {
        self.Lines
            .push("// Generated by WyrmCoil SDSL-V.".to_string());
        if let Some(namespace) = &self.Module.Namespace {
            self.Lines
                .push(format!("// namespace {}", namespace.Segments.join(".")));
        }

        for decl in &self.Module.Declarations {
            match decl {
                SdslvDecl::TypeAlias(alias) => self.EmitTypeAlias(alias),
                SdslvDecl::Stream(stream) => self.EmitStream(stream),
                SdslvDecl::Record(record) => self.EmitRecord(record),
                SdslvDecl::Shader(shader) => self.EmitShader(shader),
                SdslvDecl::Flow(flow) => self.EmitFlow(flow),
                SdslvDecl::Compile(compile) => self.EmitCompile(compile),
                SdslvDecl::Interface(interface) => {
                    self.Lines.push(format!(
                        "// interface {} omitted in HLSL M3",
                        interface.Name
                    ));
                }
            }
        }
    }

    fn EmitTypeAlias(&mut self, alias: &SdslvTypeAliasDecl) {
        if let Some(space) = &alias.SpaceAnnotation {
            self.Lines
                .push(format!("// @space({})", space.Segments.join(".")));
        }
        if let Some(mapped) = self.MapTypeFromPath(&alias.TargetType) {
            self.Lines
                .push(format!("typedef {} {};", mapped, alias.Name));
        }
    }

    fn EmitStream(&mut self, stream: &SdslvStreamDecl) {
        self.Lines.push(format!("struct {} {{", stream.Name));
        let mut texcoord_index = 0;
        let mut sv_position_emitted = false;

        for field in &stream.Fields {
            let Some(field_type) = self.MapTypeFromPath(&field.TypeName) else {
                continue;
            };

            let semantic = if self.IsPositionField(field) {
                if sv_position_emitted {
                    self.Err(&format!(
                        "stream '{}' has duplicate field mapping to SV_Position",
                        stream.Name
                    ));
                    format!("TEXCOORD{}", texcoord_index)
                } else {
                    sv_position_emitted = true;
                    "SV_Position".to_string()
                }
            } else {
                let value = format!("TEXCOORD{}", texcoord_index);
                texcoord_index += 1;
                value
            };
            if semantic == "SV_Position" {
                self.Lines
                    .push(format!("    {} {} : {};", field_type, field.Name, semantic));
            } else {
                self.Lines
                    .push(format!("    {} {} : {};", field_type, field.Name, semantic));
            }
        }
        self.Lines.push("};".to_string());
    }
    fn EmitRecord(&mut self, record: &SdslvRecordDecl) {
        self.Lines.push(format!("struct {} {{", record.Name));
        for field in &record.Fields {
            let Some(field_type) = self.MapTypeFromPath(&field.TypeName) else {
                continue;
            };
            self.Lines
                .push(format!("    {} {};", field_type, field.Name));
        }
        self.Lines.push("};".to_string());
    }

    fn EmitShader(&mut self, shader: &SdslvShaderDecl) {
        for method in &shader.Methods {
            self.EmitShaderMethodNamed(&shader.Name, method);
        }
        if !shader.GenericParameters.is_empty() {
            return;
        }

        for stage_method in &shader.StageMethods {
            self.EmitStageMethod(shader, stage_method);
        }
    }
    fn EmitCompile(&mut self, compile: &SdslvCompileDecl) {
        let generic_name = compile.GenericShader.Segments.join(".");
        let generic_shader = self.Module.Declarations.iter().find_map(|d| match d {
            SdslvDecl::Shader(s) if s.Name == generic_name => Some(s),
            _ => None,
        });
        let Some(shader) = generic_shader else {
            return;
        };
        for stage_method in &shader.StageMethods {
            self.EmitStageMethodAlias(shader, &compile.Alias, stage_method, compile);
        }
    }
    fn EmitShaderMethodNamed(&mut self, shader_name: &str, method: &SdslvFunctionDecl) {
        let Some(return_type) = self.MapTypeFromPath(&method.ReturnType) else {
            return;
        };
        let mut parameters = vec![];
        for parameter in &method.Parameters {
            let Some(mapped) = self.MapTypeFromPath(&parameter.TypeName) else {
                return;
            };
            parameters.push(format!("{} {}", mapped, parameter.Name));
        }
        self.Lines.push(format!(
            "{} {}_{}({}) {{",
            return_type,
            shader_name,
            method.Name,
            parameters.join(", ")
        ));
        if let Some(body) = &method.Body {
            let mut with_counter = 0usize;
            for statement in &body.Statements {
                for line in self.EmitStatementLines(statement, &mut with_counter) {
                    self.Lines.push(format!("    {}", line));
                }
            }
        }
        self.Lines.push("}".to_string());
    }
    fn EmitStageMethodAlias(
        &mut self,
        shader: &SdslvShaderDecl,
        alias: &str,
        method: &SdslvFunctionDecl,
        compile: &SdslvCompileDecl,
    ) {
        let mut local_method = method.clone();
        if let Some(first) = compile.TypeArguments.first() {
            if let Some(param) = local_method.Parameters.iter_mut().find(|p| {
                shader
                    .GenericParameters
                    .contains(&p.TypeName.Segments.join("."))
            }) {
                param.TypeName = first.clone();
            }
        }
        let Some(return_type) = self.MapTypeFromPath(&local_method.ReturnType) else {
            return;
        };
        let mut parameters = vec![];
        for parameter in &local_method.Parameters {
            let Some(mapped) = self.MapTypeFromPath(&parameter.TypeName) else {
                return;
            };
            parameters.push(format!("{} {}", mapped, parameter.Name));
        }
        let mut signature = format!(
            "{} {}_{}({})",
            return_type,
            alias,
            local_method.Name,
            parameters.join(", ")
        );
        if local_method.Stage.as_deref() == Some("pixel") {
            signature.push_str(" : SV_Target");
        }
        signature.push_str(" {");
        self.Lines.push(signature);
        if let Some(body) = &local_method.Body {
            let mut with_counter = 0usize;
            for statement in &body.Statements {
                for line in self.EmitStatementLines(statement, &mut with_counter) {
                    let mut text = line;
                    if text.contains("mat.BaseColor(")
                        && let Some(first) = compile.TypeArguments.first()
                    {
                        text = text.replace(
                            "mat.BaseColor(",
                            &format!("{}_BaseColor(", first.Segments.join(".")),
                        );
                    }
                    self.Lines.push(format!("    {}", text));
                }
            }
        }
        self.Lines.push("}".to_string());
    }

    fn EmitStageMethod(&mut self, shader: &SdslvShaderDecl, method: &SdslvFunctionDecl) {
        let stage_name = method.Stage.clone().unwrap_or_default();
        if stage_name == "compute" {
            self.Err(&format!(
                "unsupported stage 'compute' for HLSL M3 emission in shader '{}'",
                shader.Name
            ));
            return;
        }

        let Some(return_type) = self.MapTypeFromPath(&method.ReturnType) else {
            return;
        };

        let mut parameters = vec![];
        for parameter in &method.Parameters {
            let Some(mapped) = self.MapTypeFromPath(&parameter.TypeName) else {
                return;
            };
            parameters.push(format!("{} {}", mapped, parameter.Name));
        }

        let mut signature = format!(
            "{} {}_{}({})",
            return_type,
            shader.Name,
            method.Name,
            parameters.join(", ")
        );
        if stage_name == "pixel" {
            signature.push_str(" : SV_Target");
        }
        signature.push_str(" {");
        self.Lines.push(signature);

        if let Some(body) = &method.Body {
            let mut with_counter = 0usize;
            for statement in &body.Statements {
                for line in self.EmitStatementLines(statement, &mut with_counter) {
                    self.Lines.push(format!("    {}", line));
                }
            }
        } else {
            self.Lines
                .push("    // SDSL-V body emission not implemented yet.".to_string());
            self.Lines
                .push(format!("    return {};", self.ZeroForType(&return_type)));
        }

        self.Lines.push("}".to_string());
    }

    fn EmitStatementLines(
        &mut self,
        statement: &SdslvStatement,
        with_counter: &mut usize,
    ) -> Vec<String> {
        match statement {
            SdslvStatement::Let {
                Name,
                TypeName,
                Initializer,
            } => {
                let type_name = TypeName.Segments.join(".");
                let rendered = self.MapBuiltinType(&type_name).unwrap_or(&type_name);
                if let Some(init) = Initializer {
                    if let SdslvExpression::Switch {
                        Subject,
                        Cases,
                        ElseValue,
                        ..
                    } = init
                    {
                        let mut lines = vec![format!("{} {};", rendered, Name)];
                        lines.extend(self.EmitSwitchChainLines(
                            Subject.as_deref(),
                            Cases,
                            ElseValue,
                            &format!("{Name} = {{value}};"),
                            "if",
                        ));
                        return lines;
                    }
                    if let SdslvExpression::With { Base, Updates } = init {
                        let mut lines = vec![format!(
                            "{} {} = {};",
                            rendered,
                            Name,
                            self.EmitExpression(Base, 0)
                        )];
                        for update in Updates {
                            lines.push(format!(
                                "{}.{} = {};",
                                Name,
                                update.Field,
                                self.EmitExpression(&update.Value, 0)
                            ));
                        }
                        lines
                    } else {
                        vec![format!(
                            "{} {} = {};",
                            rendered,
                            Name,
                            self.EmitExpression(init, 0)
                        )]
                    }
                } else {
                    vec![format!("{} {};", rendered, Name)]
                }
            }
            SdslvStatement::Assign { Target, Value } => {
                if let SdslvExpression::Switch {
                    Subject,
                    Cases,
                    ElseValue,
                    ..
                } = Value
                {
                    let target_text = self.EmitExpression(Target, 0);
                    return self.EmitSwitchChainLines(
                        Subject.as_deref(),
                        Cases,
                        ElseValue,
                        &format!("{target_text} = {{value}};"),
                        "if",
                    );
                }
                if let SdslvExpression::With { Base, Updates } = Value {
                    let target_text = self.EmitExpression(Target, 0);
                    let mut lines = vec![format!(
                        "{} = {};",
                        target_text,
                        self.EmitExpression(Base, 0)
                    )];
                    for update in Updates {
                        lines.push(format!(
                            "{}.{} = {};",
                            target_text,
                            update.Field,
                            self.EmitExpression(&update.Value, 0)
                        ));
                    }
                    lines
                } else {
                    vec![format!(
                        "{} = {};",
                        self.EmitExpression(Target, 0),
                        self.EmitExpression(Value, 0)
                    )]
                }
            }
            SdslvStatement::Return { Value } => {
                if let SdslvExpression::Switch {
                    Subject,
                    Cases,
                    ElseValue,
                    ..
                } = Value
                {
                    return self.EmitSwitchChainLines(
                        Subject.as_deref(),
                        Cases,
                        ElseValue,
                        "return {value};",
                        "if",
                    );
                }
                if let SdslvExpression::With { Base, Updates } = Value {
                    let temp_name = format!("__with{}", *with_counter);
                    *with_counter += 1;
                    let mut lines = vec![format!(
                        "auto {} = {};",
                        temp_name,
                        self.EmitExpression(Base, 0)
                    )];
                    for update in Updates {
                        lines.push(format!(
                            "{}.{} = {};",
                            temp_name,
                            update.Field,
                            self.EmitExpression(&update.Value, 0)
                        ));
                    }
                    lines.push(format!("return {};", temp_name));
                    lines
                } else {
                    vec![format!("return {};", self.EmitExpression(Value, 0))]
                }
            }
            SdslvStatement::Expression { Value } => {
                vec![format!("{};", self.EmitExpression(Value, 0))]
            }
            SdslvStatement::Empty => vec![";".to_string()],
            SdslvStatement::If {
                Condition,
                ThenBody,
                ElseBody,
                ..
            } => {
                let mut lines = vec![format!("if ({}) {{", self.EmitExpression(Condition, 0))];
                for nested in ThenBody {
                    for nested_line in self.EmitStatementLines(nested, with_counter) {
                        lines.push(format!("    {}", nested_line));
                    }
                }
                lines.push("}".to_string());
                if let Some(else_body) = ElseBody {
                    lines.push("else {".to_string());
                    for nested in else_body {
                        for nested_line in self.EmitStatementLines(nested, with_counter) {
                            lines.push(format!("    {}", nested_line));
                        }
                    }
                    lines.push("}".to_string());
                }
                lines
            }
        }
    }

    fn EmitSwitchChainLines(
        &mut self,
        subject: Option<&SdslvExpression>,
        cases: &[SdslvSwitchCase],
        else_value: &SdslvExpression,
        template: &str,
        first_keyword: &str,
    ) -> Vec<String> {
        let mut lines = vec![];
        if cases.is_empty() {
            self.Err("switch expression is not supported in this expression context in M55c");
            return vec![
                "/* switch expression is not supported in this expression context in M55c */"
                    .to_string(),
            ];
        }
        for (index, case) in cases.iter().enumerate() {
            let keyword = if index == 0 { first_keyword } else { "else if" };
            let condition = if let Some(subject) = subject {
                format!(
                    "{} == {}",
                    self.EmitExpression(subject, 0),
                    self.EmitExpression(&case.Condition, 0)
                )
            } else {
                self.EmitExpression(&case.Condition, 0)
            };
            lines.push(format!("{} ({}) {{", keyword, condition));
            lines.push(format!(
                "    {}",
                template.replace("{value}", &self.EmitExpression(&case.Value, 0))
            ));
            lines.push("}".to_string());
        }
        lines.push("else {".to_string());
        lines.push(format!(
            "    {}",
            template.replace("{value}", &self.EmitExpression(else_value, 0))
        ));
        lines.push("}".to_string());
        lines
    }

    fn EmitExpression(&self, expression: &SdslvExpression, parent_prec: u8) -> String {
        match expression {
            SdslvExpression::Identifier(x) => x.clone(),
            SdslvExpression::IntegerLiteral(x) => x.clone(),
            SdslvExpression::FloatLiteral(x) => x.clone(),
            SdslvExpression::StringLiteral(x) => format!("\"{}\"", x),
            SdslvExpression::BoolLiteral(v) => {
                if *v {
                    "true".to_string()
                } else {
                    "false".to_string()
                }
            }
            SdslvExpression::FieldAccess { Base, Field } => {
                format!("{}.{}", self.EmitExpression(Base, 3), Field)
            }
            SdslvExpression::Call { Callee, Arguments } => {
                let mut rendered = vec![];
                for arg in Arguments {
                    rendered.push(self.EmitExpression(arg, 0));
                }
                format!(
                    "{}({})",
                    self.EmitExpression(Callee, 3),
                    rendered.join(", ")
                )
            }
            SdslvExpression::Unary { Operand, .. } => {
                format!("-{}", self.EmitExpression(Operand, 3))
            }
            SdslvExpression::Binary {
                Left,
                Operator,
                Right,
            } => {
                let (op, prec) = match Operator {
                    SdslvBinaryOperator::Add => ("+", 2),
                    SdslvBinaryOperator::Subtract => ("-", 2),
                    SdslvBinaryOperator::Multiply => ("*", 3),
                    SdslvBinaryOperator::Divide => ("/", 3),
                    SdslvBinaryOperator::Equal => ("==", 1),
                    SdslvBinaryOperator::NotEqual => ("!=", 1),
                    SdslvBinaryOperator::Less => ("<", 1),
                    SdslvBinaryOperator::LessEqual => ("<=", 1),
                    SdslvBinaryOperator::Greater => (">", 1),
                    SdslvBinaryOperator::GreaterEqual => (">=", 1),
                };
                let text = format!(
                    "{} {} {}",
                    self.EmitExpression(Left, prec),
                    op,
                    self.EmitExpression(Right, prec + 1)
                );
                if prec < parent_prec {
                    format!("({})", text)
                } else {
                    text
                }
            }
            SdslvExpression::With { .. } => "/*with-unsupported*/".to_string(),
            SdslvExpression::Switch { .. } => {
                "/* switch expression is not supported in this expression context in M55c */"
                    .to_string()
            }
        }
    }
    fn IsPositionField(&self, field: &SdslvFieldDecl) -> bool {
        if field.Name == "Position" && field.TypeName.Segments.join(".") == "ClipPosition4" {
            return true;
        }
        if let Some(alias) = self.AliasByName.get(&field.TypeName.Segments.join("."))
            && let Some(space) = &alias.SpaceAnnotation
        {
            return space.Segments.join(".") == "clip.position";
        }
        false
    }

    fn MapTypeFromPath(&mut self, path: &SdslvPath) -> Option<String> {
        self.ResolveTypeName(&path.Segments.join("."), 0)
    }

    fn ResolveTypeName(&mut self, type_name: &str, depth: usize) -> Option<String> {
        if depth > 8 {
            self.Err(&format!(
                "type alias cycle or depth limit on '{}'",
                type_name
            ));
            return None;
        }

        if let Some(mapped) = self.MapBuiltinType(type_name) {
            return Some(mapped.to_string());
        }

        if let Some(alias) = self.AliasByName.get(type_name) {
            return self.ResolveTypeName(&alias.TargetType.Segments.join("."), depth + 1);
        }

        if self.IsKnownAggregateType(type_name) {
            return Some(type_name.to_string());
        }

        self.Err(&format!("unknown type '{}' in HLSL emission", type_name));
        None
    }

    fn IsKnownAggregateType(&self, type_name: &str) -> bool {
        self.Module.Declarations.iter().any(|decl| match decl {
            SdslvDecl::Stream(stream) => stream.Name == type_name,
            SdslvDecl::Record(record) => record.Name == type_name,
            SdslvDecl::Shader(shader) => shader.Name == type_name,
            _ => false,
        })
    }

    fn MapBuiltinType(&self, type_name: &str) -> Option<&'static str> {
        match type_name {
            "f32" => Some("float"),
            "float" => Some("float"),
            "float2" => Some("float2"),
            "float3" => Some("float3"),
            "float4" => Some("float4"),
            "float4x4" => Some("float4x4"),
            "i32" => Some("int"),
            "u32" => Some("uint"),
            "bool" => Some("bool"),
            _ => None,
        }
    }

    fn ZeroForType(&self, type_name: &str) -> &'static str {
        match type_name {
            "float" | "float2" | "float3" | "float4" | "float4x4" => "0",
            "int" | "uint" => "0",
            "bool" => "false",
            _ => "0",
        }
    }

    fn EmitFlow(&mut self, flow: &SdslvFlowDecl) {
        let Some(return_type) = self.MapTypeFromPath(&flow.ReturnType) else {
            return;
        };
        if !Self::IsLowerableValueType(&return_type) {
            self.Err(&format!("flow '{}' returns '{}', which cannot be lowered to an HLSL value function in SDSL-V M13", flow.Name, flow.ReturnType.Segments.join(".")));
            return;
        }
        let mut state_by_name = HashMap::new();
        for state in &flow.States {
            state_by_name.insert(state.Name.clone(), state);
        }
        if let Some(cycle_state) = self.FindFlowCycle(flow, &state_by_name) {
            self.Err(&format!(
                "flow '{}' contains a state cycle involving '{}'",
                flow.Name, cycle_state
            ));
            return;
        }
        let mut memo = HashMap::new();
        for state in &flow.States {
            if !self.StateAlwaysReturns(flow, state, &state_by_name, &mut memo) {
                self.Err(&format!(
                    "flow '{}' has a non-returning path through state '{}'",
                    flow.Name, state.Name
                ));
                return;
            }
        }
        let mut parameters = vec![];
        for p in &flow.Parameters {
            let Some(mapped) = self.MapTypeFromPath(&p.TypeName) else {
                return;
            };
            parameters.push(format!("{} {}", mapped, p.Name));
        }
        self.Lines.push(format!(
            "{} {}({}) {{",
            return_type,
            flow.Name,
            parameters.join(", ")
        ));
        if let Some(board) = &flow.Board {
            for field in &board.Fields {
                let Some(mapped) = self.MapTypeFromPath(&field.TypeName) else {
                    return;
                };
                let Some(default) = Self::DefaultValueForType(&mapped) else {
                    self.Err(&format!("flow '{}' board field '{}' of type '{}' cannot be lowered with a default value in SDSL-V M13", flow.Name, field.Name, field.TypeName.Segments.join(".")));
                    return;
                };
                self.Lines
                    .push(format!("    {} {} = {};", mapped, field.Name, default));
            }
            if !board.Fields.is_empty() {
                self.Lines.push(String::new());
            }
        }
        let entry = &flow.States[0];
        let mut ctx = FlowLowerContext {
            StateByName: state_by_name,
            Visiting: HashSet::new(),
        };
        self.EmitFlowStateStatements(flow, &entry.Statements, 1, &mut ctx);
        self.Lines.push("}".to_string());
    }

    fn EmitFlowStateStatements(
        &mut self,
        flow: &SdslvFlowDecl,
        statements: &[SdslvFlowStatement],
        indent: usize,
        ctx: &mut FlowLowerContext<'_>,
    ) {
        for statement in statements {
            match statement {
                SdslvFlowStatement::BoardAssign { Field, Value, .. } => {
                    self.Lines.push(format!(
                        "{}{} = {};",
                        Self::Indent(indent),
                        Field,
                        self.EmitFlowExpression(Value)
                    ));
                }
                SdslvFlowStatement::Return(value) => {
                    self.Lines.push(format!(
                        "{}return {};",
                        Self::Indent(indent),
                        self.EmitFlowExpression(value)
                    ));
                }
                SdslvFlowStatement::Goto(path) => {
                    let name = path.Segments.join(".");
                    if let Some(target) = ctx.StateByName.get(&name).copied() {
                        if !ctx.Visiting.insert(name.clone()) {
                            self.Err(&format!(
                                "flow '{}' contains a state cycle involving '{}'",
                                flow.Name, name
                            ));
                            return;
                        }
                        self.EmitFlowStateStatements(flow, &target.Statements, indent, ctx);
                        ctx.Visiting.remove(&name);
                    } else {
                        self.Err(&format!(
                            "goto targets unknown state '{}' in flow '{}'",
                            name, flow.Name
                        ));
                    }
                }
                SdslvFlowStatement::When(when) => {
                    for (index, case) in when.Cases.iter().enumerate() {
                        let kw = if index == 0 { "if" } else { "else if" };
                        self.Lines.push(format!(
                            "{}{} ({}) {{",
                            Self::Indent(indent),
                            kw,
                            self.EmitFlowExpression(&case.Condition)
                        ));
                        self.EmitFlowAction(flow, &case.Action, indent + 1, ctx);
                        self.Lines.push(format!("{}}}", Self::Indent(indent)));
                    }
                    if let Some(action) = &when.ElseAction {
                        self.Lines.push(format!("{}else {{", Self::Indent(indent)));
                        self.EmitFlowAction(flow, action, indent + 1, ctx);
                        self.Lines.push(format!("{}}}", Self::Indent(indent)));
                    }
                }
            }
        }
    }

    fn EmitFlowAction(
        &mut self,
        flow: &SdslvFlowDecl,
        action: &SdslvFlowAction,
        indent: usize,
        ctx: &mut FlowLowerContext<'_>,
    ) {
        match action {
            SdslvFlowAction::Return(v) => self.Lines.push(format!(
                "{}return {};",
                Self::Indent(indent),
                self.EmitFlowExpression(v)
            )),
            SdslvFlowAction::Goto(path) => {
                let name = path.Segments.join(".");
                if let Some(target) = ctx.StateByName.get(&name).copied() {
                    if !ctx.Visiting.insert(name.clone()) {
                        self.Err(&format!(
                            "flow '{}' contains a state cycle involving '{}'",
                            flow.Name, name
                        ));
                        return;
                    }
                    self.EmitFlowStateStatements(flow, &target.Statements, indent, ctx);
                    ctx.Visiting.remove(&name);
                } else {
                    self.Err(&format!(
                        "goto targets unknown state '{}' in flow '{}'",
                        name, flow.Name
                    ));
                }
            }
        }
    }

    fn EmitFlowExpression(&self, expression: &SdslvExpression) -> String {
        self.EmitExpression(&Self::RewriteBoardRefs(expression), 0)
    }
    fn RewriteBoardRefs(expression: &SdslvExpression) -> SdslvExpression {
        match expression {
            SdslvExpression::FieldAccess { Base, Field } => {
                if let SdslvExpression::Identifier(name) = &**Base
                    && name == "board"
                {
                    return SdslvExpression::Identifier(Field.clone());
                }
                SdslvExpression::FieldAccess {
                    Base: Box::new(Self::RewriteBoardRefs(Base)),
                    Field: Field.clone(),
                }
            }
            SdslvExpression::Call { Callee, Arguments } => SdslvExpression::Call {
                Callee: Box::new(Self::RewriteBoardRefs(Callee)),
                Arguments: Arguments.iter().map(Self::RewriteBoardRefs).collect(),
            },
            SdslvExpression::Binary {
                Left,
                Operator,
                Right,
            } => SdslvExpression::Binary {
                Left: Box::new(Self::RewriteBoardRefs(Left)),
                Operator: *Operator,
                Right: Box::new(Self::RewriteBoardRefs(Right)),
            },
            SdslvExpression::Unary { Operator, Operand } => SdslvExpression::Unary {
                Operator: *Operator,
                Operand: Box::new(Self::RewriteBoardRefs(Operand)),
            },
            _ => expression.clone(),
        }
    }
    fn FindFlowCycle(
        &self,
        flow: &SdslvFlowDecl,
        states: &HashMap<String, &SdslvFlowState>,
    ) -> Option<String> {
        let mut visited = HashSet::new();
        let mut stack = HashSet::new();
        for state in &flow.States {
            if self.VisitCycleState(state, states, &mut visited, &mut stack) {
                return Some(state.Name.clone());
            }
        }
        None
    }
    fn VisitCycleState(
        &self,
        state: &SdslvFlowState,
        states: &HashMap<String, &SdslvFlowState>,
        visited: &mut HashSet<String>,
        stack: &mut HashSet<String>,
    ) -> bool {
        if stack.contains(&state.Name) {
            return true;
        }
        if !visited.insert(state.Name.clone()) {
            return false;
        }
        stack.insert(state.Name.clone());
        for target in Self::CollectGotoTargets(&state.Statements) {
            if let Some(next) = states.get(&target)
                && self.VisitCycleState(next, states, visited, stack)
            {
                return true;
            }
        }
        stack.remove(&state.Name);
        false
    }
    fn CollectGotoTargets(statements: &[SdslvFlowStatement]) -> Vec<String> {
        let mut out = vec![];
        for st in statements {
            match st {
                SdslvFlowStatement::Goto(path) => out.push(path.Segments.join(".")),
                SdslvFlowStatement::When(when) => {
                    for c in &when.Cases {
                        if let SdslvFlowAction::Goto(path) = &c.Action {
                            out.push(path.Segments.join("."));
                        }
                    }
                    if let Some(SdslvFlowAction::Goto(path)) = &when.ElseAction {
                        out.push(path.Segments.join("."));
                    }
                }
                _ => {}
            }
        }
        out
    }
    fn StateAlwaysReturns(
        &self,
        flow: &SdslvFlowDecl,
        state: &SdslvFlowState,
        states: &HashMap<String, &SdslvFlowState>,
        memo: &mut HashMap<String, bool>,
    ) -> bool {
        if let Some(v) = memo.get(&state.Name) {
            return *v;
        }
        let result = self.StatementsAlwaysReturn(flow, &state.Statements, states, memo);
        memo.insert(state.Name.clone(), result);
        result
    }
    fn StatementsAlwaysReturn(
        &self,
        flow: &SdslvFlowDecl,
        statements: &[SdslvFlowStatement],
        states: &HashMap<String, &SdslvFlowState>,
        memo: &mut HashMap<String, bool>,
    ) -> bool {
        for st in statements {
            match st {
                SdslvFlowStatement::Return(_) => return true,
                SdslvFlowStatement::BoardAssign { .. } => {}
                SdslvFlowStatement::Goto(path) => {
                    let name = path.Segments.join(".");
                    let Some(target) = states.get(&name) else {
                        return false;
                    };
                    return self.StateAlwaysReturns(flow, target, states, memo);
                }
                SdslvFlowStatement::When(when) => {
                    let mut ok = true;
                    for c in &when.Cases {
                        ok &= self.ActionAlwaysReturns(flow, &c.Action, states, memo);
                    }
                    ok &= when
                        .ElseAction
                        .as_ref()
                        .map(|x| self.ActionAlwaysReturns(flow, x, states, memo))
                        .unwrap_or(false);
                    if ok {
                        return true;
                    } else {
                        return false;
                    }
                }
            }
        }
        false
    }
    fn ActionAlwaysReturns(
        &self,
        flow: &SdslvFlowDecl,
        action: &SdslvFlowAction,
        states: &HashMap<String, &SdslvFlowState>,
        memo: &mut HashMap<String, bool>,
    ) -> bool {
        match action {
            SdslvFlowAction::Return(_) => true,
            SdslvFlowAction::Goto(path) => {
                let name = path.Segments.join(".");
                let Some(target) = states.get(&name) else {
                    return false;
                };
                self.StateAlwaysReturns(flow, target, states, memo)
            }
        }
    }
    fn IsLowerableValueType(type_name: &str) -> bool {
        matches!(
            type_name,
            "bool" | "int" | "uint" | "float" | "float2" | "float3" | "float4" | "float4x4"
        )
    }
    fn DefaultValueForType(type_name: &str) -> Option<&'static str> {
        match type_name {
            "bool" => Some("false"),
            "int" | "uint" => Some("0"),
            "float" => Some("0.0"),
            "float2" => Some("float2(0.0, 0.0)"),
            "float3" => Some("float3(0.0, 0.0, 0.0)"),
            "float4" => Some("float4(0.0, 0.0, 0.0, 0.0)"),
            _ => None,
        }
    }
    fn Indent(level: usize) -> String {
        "    ".repeat(level)
    }

    fn Err(&mut self, message: &str) {
        self.Diagnostics
            .push(SdslvDiagnostic::New(message, Self::UnknownSpan()));
    }

    fn UnknownSpan() -> SdslvSpan {
        SdslvSpan {
            Start: 0,
            End: 0,
            Line: 1,
            Column: 1,
        }
    }

    fn Finish(self) -> Result<String, Vec<SdslvDiagnostic>> {
        if self.Diagnostics.is_empty() {
            Ok(self.Lines.join("\n"))
        } else {
            Err(self.Diagnostics)
        }
    }
}
