#![allow(non_snake_case)]

use std::collections::HashMap;

use super::ast::*;
use super::diagnostic::SdslvDiagnostic;
use super::token::SdslvSpan;
use super::validation::ValidateModule;

pub fn EmitHlsl(module: &SdslvModule) -> Result<String, Vec<SdslvDiagnostic>> {
    if let Err(diagnostics) = ValidateModule(module) {
        return Err(diagnostics);
    }

    let mut emitter = HlslEmitter::New(module);
    emitter.Emit();
    emitter.Finish()
}

pub fn CompileSourceToHlsl(source: &str) -> Result<String, Vec<SdslvDiagnostic>> {
    let module = super::parser::ParseSource(source)?;
    ValidateModule(&module)?;
    EmitHlsl(&module)
}

struct HlslEmitter<'a> {
    Module: &'a SdslvModule,
    AliasByName: HashMap<String, &'a SdslvTypeAliasDecl>,
    Lines: Vec<String>,
    Diagnostics: Vec<SdslvDiagnostic>,
}

impl<'a> HlslEmitter<'a> {
    fn New(module: &'a SdslvModule) -> Self {
        let mut alias_by_name = HashMap::new();
        for decl in &module.Declarations {
            if let SdslvDecl::TypeAlias(alias) = decl {
                alias_by_name.insert(alias.Name.clone(), alias);
            }
        }
        Self {
            Module: module,
            AliasByName: alias_by_name,
            Lines: vec![],
            Diagnostics: vec![],
        }
    }

    fn Emit(&mut self) {
        self.Lines
            .push("// Generated by WyrmCoil SDSL-V.".to_string());
        if let Some(namespace) = &self.Module.Namespace {
            self.Lines
                .push(format!("// namespace {}", namespace.Segments.join(".")));
        }

        for decl in &self.Module.Declarations {
            match decl {
                SdslvDecl::TypeAlias(alias) => self.EmitTypeAlias(alias),
                SdslvDecl::Stream(stream) => self.EmitStream(stream),
                SdslvDecl::Shader(shader) => self.EmitShader(shader),
                SdslvDecl::Interface(interface) => {
                    self.Lines.push(format!(
                        "// interface {} omitted in HLSL M3",
                        interface.Name
                    ));
                }
            }
        }
    }

    fn EmitTypeAlias(&mut self, alias: &SdslvTypeAliasDecl) {
        if let Some(space) = &alias.SpaceAnnotation {
            self.Lines
                .push(format!("// @space({})", space.Segments.join(".")));
        }
        if let Some(mapped) = self.MapTypeFromPath(&alias.TargetType) {
            self.Lines
                .push(format!("typedef {} {};", mapped, alias.Name));
        }
    }

    fn EmitStream(&mut self, stream: &SdslvStreamDecl) {
        self.Lines.push(format!("struct {} {{", stream.Name));
        let mut texcoord_index = 0;
        let mut sv_position_emitted = false;

        for field in &stream.Fields {
            let Some(field_type) = self.MapTypeFromPath(&field.TypeName) else {
                continue;
            };

            let semantic = if self.IsPositionField(field) {
                if sv_position_emitted {
                    self.err(&format!(
                        "stream '{}' has duplicate field mapping to SV_Position",
                        stream.Name
                    ));
                    format!("TEXCOORD{}", texcoord_index)
                } else {
                    sv_position_emitted = true;
                    "SV_Position".to_string()
                }
            } else {
                let value = format!("TEXCOORD{}", texcoord_index);
                texcoord_index += 1;
                value
            };
            if semantic == "SV_Position" {
                self.Lines
                    .push(format!("    {} {} : {};", field_type, field.Name, semantic));
            } else {
                self.Lines
                    .push(format!("    {} {} : {};", field_type, field.Name, semantic));
            }
        }
        self.Lines.push("};".to_string());
    }

    fn EmitShader(&mut self, shader: &SdslvShaderDecl) {
        if !shader.GenericParameters.is_empty() {
            self.err(&format!(
                "cannot emit generic shader '{}' in SDSL-V M3",
                shader.Name
            ));
            return;
        }

        for stage_method in &shader.StageMethods {
            self.EmitStageMethod(shader, stage_method);
        }
    }

    fn EmitStageMethod(&mut self, shader: &SdslvShaderDecl, method: &SdslvFunctionDecl) {
        let stage_name = method.Stage.clone().unwrap_or_default();
        if stage_name == "compute" {
            self.err(&format!(
                "unsupported stage 'compute' for HLSL M3 emission in shader '{}'",
                shader.Name
            ));
            return;
        }

        let Some(return_type) = self.MapTypeFromPath(&method.ReturnType) else {
            return;
        };

        let mut parameters = vec![];
        for parameter in &method.Parameters {
            let Some(mapped) = self.MapTypeFromPath(&parameter.TypeName) else {
                return;
            };
            parameters.push(format!("{} {}", mapped, parameter.Name));
        }

        let mut signature = format!(
            "{} {}_{}({})",
            return_type,
            shader.Name,
            method.Name,
            parameters.join(", ")
        );
        if stage_name == "pixel" {
            signature.push_str(" : SV_Target");
        }
        signature.push_str(" {");
        self.Lines.push(signature);

        if let Some(body) = &method.Body {
            for statement in &body.Statements {
                self.Lines
                    .push(format!("    {}", self.EmitStatement(statement)));
            }
        } else {
            self.Lines
                .push("    // SDSL-V body emission not implemented yet.".to_string());
            self.Lines
                .push(format!("    return {};", self.ZeroForType(&return_type)));
        }

        self.Lines.push("}".to_string());
    }

    fn EmitStatement(&self, statement: &SdslvStatement) -> String {
        match statement {
            SdslvStatement::Let {
                Name,
                TypeName,
                Initializer,
            } => {
                let type_name = TypeName.Segments.join(".");
                let rendered = self.MapBuiltinType(&type_name).unwrap_or(&type_name);
                if let Some(init) = Initializer {
                    format!("{} {} = {};", rendered, Name, self.EmitExpression(init, 0))
                } else {
                    format!("{} {};", rendered, Name)
                }
            }
            SdslvStatement::Assign { Target, Value } => format!(
                "{} = {};",
                self.EmitExpression(Target, 0),
                self.EmitExpression(Value, 0)
            ),
            SdslvStatement::Return { Value } => {
                format!("return {};", self.EmitExpression(Value, 0))
            }
            SdslvStatement::Empty => ";".to_string(),
        }
    }

    fn EmitExpression(&self, expression: &SdslvExpression, parent_prec: u8) -> String {
        match expression {
            SdslvExpression::Identifier(x) => x.clone(),
            SdslvExpression::IntegerLiteral(x) => x.clone(),
            SdslvExpression::FloatLiteral(x) => x.clone(),
            SdslvExpression::BoolLiteral(v) => {
                if *v {
                    "true".to_string()
                } else {
                    "false".to_string()
                }
            }
            SdslvExpression::FieldAccess { Base, Field } => {
                format!("{}.{}", self.EmitExpression(Base, 3), Field)
            }
            SdslvExpression::Call { Callee, Arguments } => {
                let mut rendered = vec![];
                for arg in Arguments {
                    rendered.push(self.EmitExpression(arg, 0));
                }
                format!(
                    "{}({})",
                    self.EmitExpression(Callee, 3),
                    rendered.join(", ")
                )
            }
            SdslvExpression::Unary { Operand, .. } => {
                format!("-{}", self.EmitExpression(Operand, 3))
            }
            SdslvExpression::Binary {
                Left,
                Operator,
                Right,
            } => {
                let (op, prec) = match Operator {
                    SdslvBinaryOperator::Add => ("+", 1),
                    SdslvBinaryOperator::Subtract => ("-", 1),
                    SdslvBinaryOperator::Multiply => ("*", 2),
                    SdslvBinaryOperator::Divide => ("/", 2),
                };
                let text = format!(
                    "{} {} {}",
                    self.EmitExpression(Left, prec),
                    op,
                    self.EmitExpression(Right, prec + 1)
                );
                if prec < parent_prec {
                    format!("({})", text)
                } else {
                    text
                }
            }
        }
    }
    fn IsPositionField(&self, field: &SdslvFieldDecl) -> bool {
        if field.Name == "Position" && field.TypeName.Segments.join(".") == "ClipPosition4" {
            return true;
        }
        if let Some(alias) = self.AliasByName.get(&field.TypeName.Segments.join("."))
            && let Some(space) = &alias.SpaceAnnotation
        {
            return space.Segments.join(".") == "clip.position";
        }
        false
    }

    fn MapTypeFromPath(&mut self, path: &SdslvPath) -> Option<String> {
        self.ResolveTypeName(&path.Segments.join("."), 0)
    }

    fn ResolveTypeName(&mut self, type_name: &str, depth: usize) -> Option<String> {
        if depth > 8 {
            self.err(&format!(
                "type alias cycle or depth limit on '{}'",
                type_name
            ));
            return None;
        }

        if let Some(mapped) = self.MapBuiltinType(type_name) {
            return Some(mapped.to_string());
        }

        if let Some(alias) = self.AliasByName.get(type_name) {
            return self.ResolveTypeName(&alias.TargetType.Segments.join("."), depth + 1);
        }

        if self.IsKnownStream(type_name) {
            return Some(type_name.to_string());
        }

        self.err(&format!("unknown type '{}' in HLSL emission", type_name));
        None
    }

    fn IsKnownStream(&self, type_name: &str) -> bool {
        self.Module.Declarations.iter().any(|decl| match decl {
            SdslvDecl::Stream(stream) => stream.Name == type_name,
            _ => false,
        })
    }

    fn MapBuiltinType(&self, type_name: &str) -> Option<&'static str> {
        match type_name {
            "f32" => Some("float"),
            "float" => Some("float"),
            "float2" => Some("float2"),
            "float3" => Some("float3"),
            "float4" => Some("float4"),
            "float4x4" => Some("float4x4"),
            "i32" => Some("int"),
            "u32" => Some("uint"),
            "bool" => Some("bool"),
            _ => None,
        }
    }

    fn ZeroForType(&self, type_name: &str) -> &'static str {
        match type_name {
            "float" | "float2" | "float3" | "float4" | "float4x4" => "0",
            "int" | "uint" => "0",
            "bool" => "false",
            _ => "0",
        }
    }

    fn err(&mut self, message: &str) {
        self.Diagnostics
            .push(SdslvDiagnostic::New(message, Self::UnknownSpan()));
    }

    fn UnknownSpan() -> SdslvSpan {
        SdslvSpan {
            Start: 0,
            End: 0,
            Line: 1,
            Column: 1,
        }
    }

    fn Finish(self) -> Result<String, Vec<SdslvDiagnostic>> {
        if self.Diagnostics.is_empty() {
            Ok(self.Lines.join("\n"))
        } else {
            Err(self.Diagnostics)
        }
    }
}
